server:
  port: 8082

spring:
  application:
    name: groups
  data:
    mongodb:
      host: localhost
      port: 27017
      database: GroupChats
#  rabbitmq:
#    addresses: localhost:5672
#    username: bor3y
#    password: bor3y
#    listener:
#      simple:
#        default-requeue-rejected: false

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    groups: groups.queue
  routing-keys:
    internal-groups: internal.groups.routing.key